# Generated by Django 3.2.9 on 2021-11-09 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arcticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Мақала атауы')),
                ('text', models.TextField(verbose_name='Мақала тексті')),
                ('pub_date', models.DateTimeField(verbose_name='Уақыт')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Автор есімі')),
                ('text', models.CharField(max_length=200, verbose_name='Коммент')),
                ('arcticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arcticles.arcticle')),
            ],
        ),
    ]
